train:
  _target_: src.datasets.KaggleDownload
  instance_transforms: ${transforms.instance_transforms.train}
  download_name: "dla_dataset_big"
  part: "train"
val:
  _target_: src.datasets.KaggleDownload
  instance_transforms: ${transforms.instance_transforms.train}
  download_name: "dla_dataset_big"
  part: "val"
