train:
  _target_: src.datasets.YandexDownload
  instance_transforms: ${transforms.instance_transforms.train}
  download_name: ${download_name}
  part: "train"
val:
  _target_: src.datasets.YandexDownload
  instance_transforms: ${transforms.instance_transforms.train}
  download_name: ${download_name}
  part: "val"
  limit: 500
