val:
  _target_: src.datasets.YandexDownload
  instance_transforms: null
  download_name: ${download_name}
  part: "val"
test:
  _target_: src.datasets.YandexDownload
  instance_transforms: null
  download_name: ${download_name}
  part: "test"
