train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.SiSnr
    name: "SiSnri"
    compare: ${compare}
    improved: ${improved}
    use_pit: ${use_pit}
  - _target_: src.metrics.SiSdr
    name: "SiSdri"
    compare: ${compare}
    improved: ${improved}
    use_pit: ${use_pit}
  #too long to calculate
  # - _target_: src.metrics.Pesq
  #   name: "Pesq"
  #   compare: ${compare}
  #   sample_rate: ${sample_rate}
  #   use_pit: ${use_pit}
  # - _target_: src.metrics.Stoi
  #   name: "Stoi"
  #   compare: ${compare}
  #   sample_rate: ${sample_rate}
  #   use_pit: ${use_pit}
