_target_: src.model.DPRNN_TasNet
# n_feats: ${transforms.batch_transforms.train.get_spectrogram.n_mels}
# fc_hidden: 512
n_frames: 32000
input_dim: 1
enc_hidden_dim: 4   # 64 in original paper
rnn_hidden_dim: 8  # 128 in original paper
n_dprnn_blocks: 1    # 6 in original paper
n_speakers: 2
overlap: True
