_target_: src.model.DPRNN_TasNet
n_frames: 32000
input_dim: 1
enc_hidden_dim: 64   # 64 in original paper
rnn_hidden_dim: 128  # 128 in original paper
n_dprnn_blocks: 6    # 6 in original paper
n_speakers: 2
overlap: True
