defaults:
  - model: baseline
  - metrics: all_metrics
  - datasets: yandex_disk_small # we do not want to run inference on training data
  - dataloader: example
  - transforms: example
  - _self_
sample_rate: 16000
inferencer:
  device_tensors: ["audio_first", "audio_second", "audio_mix"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/model_best.pth" # path to the pretrained model
