defaults:
  - model: rtfs
  - metrics: inference
  - datasets: yandex_disk_inference
  - dataloader: train_val_dataloaders
  - transforms: rtfs
  - _self_
download_name: "dla_dataset"
batch_size: 8
num_workers: 8
sample_rate: 16000
inferencer:
  device_tensors: ["audio_first", "audio_second", "audio_mix", "video_embeddings"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "inference/rtfs" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/rtfs-net-3-v/model_best.pth" # path to the pretrained model
