defaults:
  - model: rtfs-m
  - writer: wandb
  - metrics: rtfs_training
  - datasets: yandex_disk
  - dataloader: train_val_dataloaders
  - transforms: rtfs
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0002
  weight_decay: 0.1
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 110000
loss_function:
  _target_: src.loss.AudioSiSnrRTFS
download_name: "dla_dataset"
batch_size: 12
num_workers: 12
sample_rate: 16000
trainer:
  log_step: 50
  n_epochs: 140
  epoch_len: 700
  device_tensors: ["audio_first", "audio_second", "audio_mix", "video_embeddings"] # which tensors should be on device (ex. GPU)
  resume_from: "../../saved-v/testing/model_best.pth"
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "max val_SiSnri" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 100000 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved-vc"
  dir_created: False
  parallel: False
  seed: 1
  lipreading_model_name: "resnet18_dctcn" # pretrained model from mpc001 repo (check src\utils\lipreading\load_model.py for the correct name)
  max_grad_norm: 5.0
