

val_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset: ${datasets.val}
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  pin_memory: True

test_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset: ${datasets.test}
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  pin_memory: True
